version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:80"
    depends_on:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
